"""add thumbnail

Revision ID: 08e6ae73aeb0
Revises: 3c33f5574038
Create Date: 2024-07-27 19:15:20.610995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e6ae73aeb0'
down_revision: Union[str, None] = '3c33f5574038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('thumbnail', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'channel', ['id'])
    op.create_unique_constraint(None, 'course', ['id'])
    op.create_unique_constraint(None, 'video', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'course', type_='unique')
    op.drop_constraint(None, 'channel', type_='unique')
    op.drop_column('channel', 'thumbnail')
    # ### end Alembic commands ###
