"""fixing incongruents in models course and video

Revision ID: 12dbcd89fbc9
Revises: 39c23f0a77e4
Create Date: 2024-07-24 14:19:37.082858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12dbcd89fbc9'
down_revision: Union[str, None] = '39c23f0a77e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course', 'channel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
