"""fixing courses my_courses_id=nullable

Revision ID: 21128f53a67e
Revises: 12dbcd89fbc9
Create Date: 2024-07-24 14:49:11.309446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21128f53a67e'
down_revision: Union[str, None] = '12dbcd89fbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'my_courses_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'my_courses_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
