"""refactoring image -> thumbnail to model Video and Channel

Revision ID: 39c23f0a77e4
Revises: 6f17b58dc5e0
Create Date: 2024-07-24 10:29:18.322611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c23f0a77e4'
down_revision: Union[str, None] = '6f17b58dc5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('thumbnail', sa.String(), nullable=False))
    op.drop_column('channel', 'image')
    op.add_column('video', sa.Column('thumbnail', sa.String(), nullable=False))
    op.drop_column('video', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('video', 'thumbnail')
    op.add_column('channel', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('channel', 'thumbnail')
    # ### end Alembic commands ###
