"""country optional

Revision ID: 5f3f00080a55
Revises: 08e6ae73aeb0
Create Date: 2024-07-27 19:36:44.981007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3f00080a55'
down_revision: Union[str, None] = '08e6ae73aeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('channel', 'views',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('channel', 'subs',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel', 'subs',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channel', 'views',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('channel', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
