"""delete thumbnail course

Revision ID: 6b985b9b746c
Revises: 5f3f00080a55
Create Date: 2024-07-27 21:03:23.030671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b985b9b746c'
down_revision: Union[str, None] = '5f3f00080a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'thumbnail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
