"""add thumbnail in course

Revision ID: ab491686ec62
Revises: 21128f53a67e
Create Date: 2024-07-24 15:16:02.264172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab491686ec62'
down_revision: Union[str, None] = '21128f53a67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('thumbnail', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'thumbnail')
    # ### end Alembic commands ###
