"""add my_course_id

Revision ID: b37e5c428b1a
Revises: cb659bb06151
Create Date: 2024-07-29 10:02:38.077921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37e5c428b1a'
down_revision: Union[str, None] = 'cb659bb06151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('my_courses_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'my_courses', ['my_courses_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'my_courses_id')
    # ### end Alembic commands ###
