"""drop tables

Revision ID: b6300c50176c
Revises: ae338e9c2adc
Create Date: 2024-07-26 20:41:14.760682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6300c50176c"
down_revision: Union[str, None] = "ab491686ec62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video")
    op.drop_table("course")
    op.drop_table("channel")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("thumbnail", sa.String(), nullable=False))
    # ### end Alembic commands ###
