"""delete is_active course

Revision ID: eb1b7b9faab5
Revises: 6b985b9b746c
Create Date: 2024-07-27 21:11:20.058211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb1b7b9faab5'
down_revision: Union[str, None] = '6b985b9b746c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_my_courses_id_fkey', 'course', type_='foreignkey')
    op.drop_column('course', 'is_active')
    op.drop_column('course', 'my_courses_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('my_courses_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('course', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key('course_my_courses_id_fkey', 'course', 'my_courses', ['my_courses_id'], ['id'])
    # ### end Alembic commands ###
