"""add thumbnail

Revision ID: f4ad8d3739cc
Revises: b37e5c428b1a
Create Date: 2024-07-29 21:24:03.720123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ad8d3739cc'
down_revision: Union[str, None] = 'b37e5c428b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('thumbnail', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'thumbnail')
    # ### end Alembic commands ###
